[theme]
base = "dark"
primaryColor = "#FFFFFF"
backgroundColor = "#0A0A0C"
secondaryBackgroundColor = "#121215"
textColor = "#EDEDED"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true


